# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 21:20
from __future__ import unicode_literals

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('public_file', models.FileField(blank=True, null=True, upload_to='public/', verbose_name='Archivo publico')),
                ('private_file', app.models.S3PrivateFileField(blank=True, null=True, upload_to='private/', verbose_name='Archivo privado')),
            ],
            options={
                'verbose_name_plural': 'Imagenes',
                'verbose_name': 'Imagen',
            },
        ),
    ]
